version: "2.4"

services:
  postgres:
    image: postgres:15
    mem_limit: 512m
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - /home/Documents/postgres-a:/var/lib/postgresql/data
  currency-converter:
    image: demo:2.0.0
    restart: always
    mem_limit: 512m
    ports:
      - "8008:8008"
    environment:
      URL: "${POSTGRES_URL}"
    depends_on:
      - postgres
  angular:
    image: angular-software:0.2.0-docker
    ports:
      - "4200:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf